package com.bjpowernode.javase.exception;

import org.w3c.dom.ls.LSOutput;

import java.io.FileInputStream;
import java.io.FileNotFoundException;

/*
* 异常对象的两个方法：
*     String msg = e.getMessage();
*     e.printStackTrace();   //一般都是使用这个。
*
* 我们以后查看异常的追踪信息，我们应该怎么看？可以快速的调试程序呢？
*     异常信息追踪信息，从上往下一行一行看。
*     但是需要注意的是：SUN写的代码就不用看了。主要的问题是出现在自己编写的代码上。
* */
public class ExceptionTest09 {
    public static void main(String[] args) {
        try {
            m1();
        } catch (FileNotFoundException e) {
            //获取异常的简单描述信息
            String msg = e.getMessage();
            System.out.println(msg);
            //打印异常堆栈追踪信息！！！
            //在实际的开发中，建议使用这个。养成好习惯！
            //这行代码要写上，不然出问题你也不知道！
            e.printStackTrace();
            /*
    java.io.FileNotFoundException: D:\javase-进阶\document\da20课堂笔记.txt (系统找不到指定的文件。)
	 at java.base/java.io.FileInputStream.open0(Native Method)
	 at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	 at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	 at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	 at com.bjpowernode.javase.exception.ExceptionTest09.m3(ExceptionTest09.java:31)
	 at com.bjpowernode.javase.exception.ExceptionTest09.m2(ExceptionTest09.java:27)
	 at com.bjpowernode.javase.exception.ExceptionTest09.m1(ExceptionTest09.java:23)
	 at com.bjpowernode.javase.exception.ExceptionTest09.main(ExceptionTest09.java:14)
	 因为31行出问题导致了27行
	 27行出问题导致23行
	 23行出问题导致14行
	 应该先查看31行的代码。31行是代码错误的根源。
            * */
        }
        //这里程序不耽误执行，很健壮。（服务器不会因为遇到异常而死机。）
        System.out.println("hello world!");
    }

    private static void m1() throws FileNotFoundException {
        m2();
    }

    private static void m2() throws FileNotFoundException {
        m3();
    }

    private static void m3() throws FileNotFoundException {
        new FileInputStream("D:\\javase-进阶\\document\\da20课堂笔记.txt");
    }

    ;
}
